language: cpp
branches:
  only:
    - master
    - coverity_scan
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ndDwXAfEGdr/wXOOiLQbXQxAlQR0DZfsSz8oQohc1C0Inh5gE7Zqx8rBdlTt/DIZgZtddg2eUKlo1flZ7mt38KPDulLM7gX6xmPefpaVL9Ag/piZE1cbtz5VR59+7Z38/wkaJszQZ/ciw3WKDGD46V4TGDXXT24JGSwvc9R3VIZXNzdRX3pn47/43hSAr3/E7LU65aVx+bX1YfT7mjWPCvcbbQioYeugEhcfIUPxG3wmMIcoSqP6BQaWaxqhhPSvV6kxyR+nBo7tNwDlV9+7Fw7Dh5D6Hi1/OD7NdJlLwPq0OL66sMvu81sSX9cby5gsWQUqruce5VK4RtrPBM3lYKNjEYhEV5zTIi67293tcqHnECbLJHUWfB+p6Xh0nFekHPZv5zzmHAk/r74RuOyHxH/gMzV/GzStcuZhS4ulDgoCHgeiQMecHbzx+gK494EE+CBZfur2g1bOeqsL9hZ4zI5CzqX/5RpLJk1dehSzCLgPsfx1QZpV3rEdKUIx+EiNEIEay9/ERAX+Xpc4h7KfH7ObUTqkVx55H/dP+joL9nRovhe2ybyg6xuR4LD4oz1E5FKnD2ja6jUYwnRlRgYKlcQ9bwF+Ts/3BFM7LextPc0A8z6KwxhxmPGvsquSUiznzELBbLHIPetvGnGSslUHmIqa3Aez/1dR7WPi1faztys="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ea4k/klog"
      description: "Build submitted via Travis-CI. KLog is a multiplatform free hamradio logger."
    notification_email: jaime@robles.es
    build_command_prepend: "cov-configure --comptype gcc --compiler gcc-4.8"
    build_command: make
    branch_pattern: coverity_scan

matrix:
  include:
  - os: linux
    arch: amd64
    dist: focal
    
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install qtbase5-dev libsqlite3-dev
      - sudo apt-get -y install libhamlib++-dev libqt5serialport5-dev libqt5charts5-dev qt5-default qttools5-dev-tools
    
    compiler:
      - gcc
      
    before_script:
      - qmake KLog.pro
    
    script:
      - make
