language: cpp
sudo: required
dist: bionic
compiler: gcc
os: linux
branches:
  only:
    - master
    - devel
before_install:
 - sudo apt-get update
 - sudo apt-get -y install qtbase5-dev libsqlite3-dev
 - sudo apt-get -y install libhamlib++-dev libqt5serialport-dev libqt5charts5-dev qt5-default qttools5-dev-tools
script:
 - qmake -project
 - qmake KLog.pro
 - make 
