language: cpp
branches:
  only:
    - master
matrix:
  include:
  - os: linux
    arch: amd64
    sudo: required
    dist: focal
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install qtbase5-dev libsqlite3-dev
      - sudo apt-get -y install libhamlib++-dev libqt5serialport5-dev libqt5charts5-dev qt5-default qttools5-dev-tools
      - sudo apt-get install -y lcov
      - gem install coveralls-lcov
    compiler:
      - gcc
    script:
      - qmake -project
      - qmake KLog.pro
      - make check
      - make
    after_success:
      - lcov --compat-libtool --directory . --capture --output-file coverage.info
      - coveralls-lcov coverage.info

