language: cpp
branches:
  only:
    - master
matrix:
  include:
  - os: linux
    services:
    - docker
    dist: focal
    install:
    - devscripts/buildWithDocker.sh
    script:
    - docker run -v "$PWD":/Work/klog "$DOCKER_USERNAME"/devel-qt-5.15.2:v0/Work/klog/devscripts/buildWithDocker.sh
    
