language: cpp
branches:
  only:
    - master
matrix:
  include:
  - os: linux
    services:
    - docker
    arch: amd64
    sudo: required
    dist: focal
    before_install:
    - docker load -i docker_images/images.tar || true
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker pull "$DOCKER_USERNAME"/devel-qt-5.15.2:v0
    script:
    - docker run -ti -v "$PWD":/Work/klog "$DOCKER_USERNAME"/devel-qt-5.15.2:v0/Work/klog/devscripts/buildWithDocker.sh
    cache:
      directories:
      - docker_images
    before_cache:
    - docker save -o docker_images/images.tar $(docker images -a -q)
    
