language: cpp
sudo: required
dist: bionic
compiler: gcc
os: linux
branches:
  only:
    - master
    - devel
before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev libsqlite3-dev
 - sudo apt-get install qtbase5-dev, libhamlib++-dev, libqt5serialport-dev libqt5charts5-devqt5-default qttools5-dev-tools
script:
 - qmake -project
 - qmake KLog.pro
 - make 
