environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      BUILD_TARGET: linux

install:
  - sh: 'sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-bionic'
  - sh: 'sudo apt update'
  - sh: 'sudo apt install -y g++ make qt5-qmake qtbase5-dev qttools5-dev libqt5charts5-dev libqt5sql5-sqlite libhamlib-dev libqt5serialport5-dev'
  - sh: 'sudo apt-get upgrade -y'
  - sh: 'ls /opt/'

build_script:
  - qmake -qt=qt5 KLog.pro
  - make
