version: build{build}

image:
  - Ubuntu

  - sh: sudo add-apt-repository -y ppa:beineri/opt-qt-5.10.1-xenial
  - sh: sudo apt-get -qq update
  - sh: 'sudo apt install -qqy g++ make qt5-qmake qtbase5-dev qttools5-dev libqt5charts5-dev libqt5sql5-sqlite libhamlib-dev libqt5serialport5-dev'
  - sh: source /opt/qt510/bin/qt510-env.sh
  - sh: 'ls /opt/'

build_script:
  - qmake -qt=qt5 KLog.pro
  - make
