version: build{build}

image:
  - Ubuntu2004

install:
  - sh: sudo apt-get -qq update
  - sh: sudo apt install -qqy make qmake6 qt6-base-dev qt6-declarative-dev libhamlib-dev build-essential libgl1-mesa-dev qt6-serialport-dev qt6-positioning-dev qt6-charts-dev qt6-l10n-tools
build_script:
  - qmake KLog.pro
  - make
